version: '3'
services:
  ascent-discovery:
    image: ascent/ascent-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=aws-ci
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8761/health"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
        - ascentnet
    ports:
        - 8761
  
  ascent-config:
    image: ascent/ascent-config
    ports:
      - 8760
    environment:
      - SPRING_PROFILES_ACTIVE=aws-ci
      - VAULT_ADDR=https://${VAULT_HOST}:8200
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_HOST=${VAULT_HOST}
      - VAULT_SCHEME=https
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8760/actuator/health"]
      interval: 60s
      timeout: 10s
      retries: 3
    depends_on:
      - ascent-discovery
    networks:
    - ascentnet

  ascent-gateway:
    image: ascent/ascent-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=aws-ci
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8760/actuator/health"]
      interval: 60s
      timeout: 10s
      retries: 3
    networks:
        - ascentnet
    depends_on:
      - ascent-config
      - ascent-discovery
    ports:
        - 8762
  
networks:
  ascentnet:
    driver: overlay