version: '3.3'
services:

  ascent-gateway:
    image: ascent/ascent-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker-demo
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8762/actuator/health"]
      interval: 60s
      timeout: 10s
      retries: 3
    networks:
        - ascentnet
    depends_on:
      - ascent-config
    ports:
        - 8762:8762