version: '3.3'
services:
  ascent-amqp:
    image: ascent/rabbitmq
    environment:
      - 'VAULT_TOKEN=${VAULT_TOKEN}'
      - 'VAULT_ADDR=${VAULT_ADDR}'
    networks:
      ascentnet:
        aliases:
          - rabbit
  consul:
    image: 'consul:1.0.2'
    networks:
      - ascentnet
  ascent-discovery:
    image: ascent/ascent-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-aws-ci}
      - 'VAULT_ADDR=${VAULT_ADDR}'
      - 'VAULT_TOKEN=${VAULT_TOKEN}'
    networks:
      - ascentnet
    ports:
      - 8761
  ascent-config:
    image: ascent/ascent-config
    ports:
      - 8760
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-aws-ci}
      - 'VAULT_ADDR=${VAULT_ADDR}'
      - 'VAULT_TOKEN=${VAULT_TOKEN}'
      - 'VAULT_HOST=${VAULT_HOST}'
      - 'VAULT_PORT=${VAULT_PORT:-8200}'
      - VAULT_SCHEME=https
    depends_on:
      - ascent-discovery
    networks:
      - ascentnet
  ascent-gateway:
    image: ascent/ascent-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-aws-ci}
      - 'VAULT_ADDR=${VAULT_ADDR}'
      - 'VAULT_TOKEN=${VAULT_TOKEN}'
    networks:
      - ascentnet
    depends_on:
      - ascent-config
      - ascent-discovery
    ports:
      - 8762

networks:
  ascentnet:
    driver: overlay
