server:
  port: ${gateway.server.port:8762}
info:  
  build:
    version:  "@project.version@"
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"  
zuul:
  prefix: /api
  retryable: true
  sensitiveHeaders: Cookie, Set-Cookie
#  Uncomment to disable services automatically registering in Zuul
#  ignoredServices: '*'     
endpoints:
  health:
    sensitive: false
security:
  user:
    name: ${ascent.security.username:admin}
    password: ${ascent.security.password:default}
#  logging level enabling for debug, info, trace, error
logging: 
  level:
    gov:
      va:
        ascent: INFO
        ascent.gateway: INFO
    org:
      springframework: 
        security: WARN
        cloud:
          sleuth: 
            log: INFO
            trace: INFO  
            instrument:
              web: WARN
              rxjava: WARN
#  hystrix command overrides
hystrix:
  command:
    default:
      metrics:
        rollingStats:
          # This property sets the duration of the statistical rolling window, in milliseconds. 
          # This is how long Hystrix keeps metrics for the circuit breaker to use and for publishing 
          # Default Value: 10000
          timeInMilliseconds: 20000
        # This property sets the time to wait, in milliseconds, between allowing health snapshots to be taken that calculate 
        # success and error percentages and affect circuit breaker status. 
        # Default Value: 500
        healthSnapshot: 
          intervalInMilliseconds: 1000
      circuitBreaker:
        # This property sets the amount of time, after tripping the circuit, to reject requests 
        # before allowing attempts again to determine if the circuit should again be closed.
        # Default Value: 5000
        sleepWindowInMilliseconds: 10000
        # This property sets the minimum number of requests in a rolling window that will trip the circuit.
        # Default Value: 20
        requestVolumeThreshold: 4
      execution:
        isolation:
          thread:
            # This property sets the time in milliseconds after which the caller will observe a timeout and walk away from the 
            # command execution. Hystrix marks the HystrixCommand as a TIMEOUT, and performs fallback logic. Note that there 
            # is configuration for turning off timeouts per-command, if that is desired (see command.timeout.enabled). 
            # IMPORTANT NOTE: THIS TIMEOUT VALUE MUST BE GREATER THAN ANY SERVICE TIMEOUT TO AVOID ERRORS
            # Default Value: 1000
            timeoutInMilliseconds: 20000
#  Ribbon Read Timeout for Ascent Demo Service requests
ascent-demo-service:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 5000
#  Default Ribbon Read Timeout for ALL the requests
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 5000
  # client side to refresh every 10 seconds
  ServerListRefreshInterval: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
ascent:
  security:
    jwt:
      filter-process-url: /api/**
      enabled: false
      # any urls to be excluded by the filter
      excludeUrls: "/api/**/v2/api-docs, /api/**/configuration/ui, /api/**/swagger-resources, /api/**/configuration/security, /api/**/swagger-ui.html, /api/**/webjars/**, /**/token, /api/**/beans, /api/**/beans, /api/**/autoconfig, /api/**/configprops, /api/**/dump, /api/**/env, /api/**/health, /api/**/info, /api/**/metrics, /api/**/mappings, /api/**/trace, /api/**/loggers"
# Sleuth configuration     
# To skip specific patterns being exported, added few more customs on top of default skip pattern
# see org.springframework.cloud.sleuth.instrument.web.TraceFilter.DEFAULT_SKIP_PATTERN
spring.sleuth.web.skipPattern: (/api/.*/webjars.*|/api/.*/v2/api-docs.*|/api/.*/swagger-resources.*|/api/.*/swagger-ui.*|/api-docs.*|/manage.*|/mappings|/trace|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream)

spring.sleuth.scheduled.skipPattern: "^org.*TestBeanWithScheduledMethodToBeIgnored$"
# comma separated list of matchers
spring.sleuth.rxjava.schedulers.ignoredthreads: HystixMetricPoller,^RxComputation.*$,^RxIoScheduler.*$
---
spring:
  profiles: local-int
  sleuth:
    stream:
      enabled: false
  zipkin:
    enabled: true
    baseUrl: http://localhost:8700
management:
  health:
    rabbit:
      enabled: false
